name: 'Save Coverage Artifacts'
description: 'Guarda los reportes de cobertura en la rama de artefactos'
inputs:
  gh-token:
    description: 'GitHub Token'
    required: true
  artifacts-branch:
    description: 'Nombre de la rama para guardar artefactos'
    required: false
    default: 'artifacts'
  reports-path:
    description: 'Ruta relativa en el repositorio donde se encuentran los reportes de cobertura'
    required: false
    default: 'deployments/tests/reports'
runs:
  using: 'composite'
  steps:
    - name: Checkout code (if needed for context)
      uses: actions/checkout@v3

    - name: Save artifacts to branch
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        COMMIT_ID: ${{ github.sha }}
        BRANCH_NAME: ${{ github.ref_name }}
        REPO_NAME: ${{ github.repository }}
        ARTIFACTS_BRANCH: ${{ inputs.artifacts-branch }}
        REPORTS_PATH: ${{ inputs.reports-path }}
      run: |
        echo "Configurando git user"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        echo "Verificando si existe la rama ${ARTIFACTS_BRANCH}"
        BRANCH_EXISTS=$(git ls-remote --heads https://${GH_TOKEN}@github.com/${REPO_NAME}.git ${ARTIFACTS_BRANCH})
        if [ -n "$BRANCH_EXISTS" ]; then
          echo "La rama ${ARTIFACTS_BRANCH} existe. Clonándola"
          git clone --branch ${ARTIFACTS_BRANCH} --single-branch https://${GH_TOKEN}@github.com/${REPO_NAME}.git artifacts-repo
          cd artifacts-repo
        else
          echo "La rama ${ARTIFACTS_BRANCH} no existe. Creando una nueva rama huérfana"
          mkdir artifacts-repo
          cd artifacts-repo
          git init
          git checkout --orphan ${ARTIFACTS_BRANCH}
          git commit --allow-empty -m "Commit inicial para la rama ${ARTIFACTS_BRANCH}"
          git remote add origin https://${GH_TOKEN}@github.com/${REPO_NAME}.git
          git push --set-upstream origin ${ARTIFACTS_BRANCH}
        fi

        echo "Creando directorios para los artefactos"
        mkdir -p ${BRANCH_NAME}/${COMMIT_ID}
        cp ../${REPORTS_PATH}/* ${BRANCH_NAME}/${COMMIT_ID}/
        mkdir -p ${BRANCH_NAME}/latest
        cp ../${REPORTS_PATH}/* ${BRANCH_NAME}/latest/

        echo "Agregando README al repositorio de artefactos"
        README_CONTENT="# Repositorio de Artefactos\n\nContiene reportes de test y otros artefactos del proyecto."
        echo -e $README_CONTENT > README.md

        echo "Agregando artefactos y README a git"
        git add README.md
        git add ${BRANCH_NAME}/${COMMIT_ID}/*
        git add ${BRANCH_NAME}/latest/*

        git commit -m "Agregar artefactos y README para commit $COMMIT_ID en la rama $BRANCH_NAME"
        
        echo "Pushing artefactos a la rama ${ARTIFACTS_BRANCH}"
        git push origin ${ARTIFACTS_BRANCH}
        
        echo "Artefactos subidos exitosamente a la rama ${ARTIFACTS_BRANCH}"
