name: Run Tests

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🏗️ Build test image
        run: |
          docker build --progress=plain -t my-test-image -f docker_images/testing/Dockerfile.testing .

      - name: 🚀 Run tests in container
        run: |
          docker run \
            --name my-tests \
            --network=host \
            -e CI=true \
            -e GITHUB_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/test_db \
            -e GITHUB_DATABASE_MONGODB=mongodb://localhost:27017 \
            -e GITHUB_DATABASE_REDIS=redis://localhost:6379 \
            -v ${{ github.workspace }}/artifacts:/app/artifacts \
            my-test-image

      - name: 📥 Copiar reportes del contenedor (solo si existen)
        run: |
          mkdir -p coverage-reports/htmlcov
          docker cp my-tests:/app/coverage.xml coverage-reports/ || echo "⚠️ coverage.xml not found"
          docker cp my-tests:/app/htmlcov/. coverage-reports/htmlcov/ || echo "⚠️ htmlcov directory not found"

          # Verificamos si de verdad hay coverage:
          if [ -f coverage-reports/coverage.xml ] || [ -d coverage-reports/htmlcov ]; then
            echo "✅ Se copiaron reportes de cobertura correctamente."
          else
            echo "⚠️ No se encontró coverage.xml ni htmlcov."
          fi

      - name: Guardar coverage
        uses: ./.github/actions/save-coverage
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: 'artifacts'
          reports-path: 'coverage-reports'
